name: TrackManager
main: com.sleelin.TrackManager.TrackManager
version: 0.1.0
depend:
- Permissions
author: Sleelin
description: Adds track management and promotion to Permissions Plus!
commands:
  track:
    description: base command used for managing and manipulating tracks.
    usage: /track [add|remove|modify] - Used to manipulate tracks.